# Generated by Django 3.1 on 2020-10-11 09:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20201011_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
