# Generated by Django 3.1 on 2020-10-10 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='background',
            field=models.CharField(choices=[('blue', 'src'), ('green', 'src')], default='blue', max_length=5),
        ),
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[('LGN', 'legend'), ('BS', 'basic')], default='BS', max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='img',
            field=models.ImageField(upload_to='game/'),
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ManyToManyField(blank=True, to='game.Card')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Deck', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
